services:
  api:
    build: .
    command: uvicorn market_scanner.app:app --host 0.0.0.0 --port 8010
    env_file: .env
    depends_on:
      - db
    ports:
      - "8010:8010"

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scanner
    ports:
      - "5433:5432"

# ONNYX | ONNX | DJM | DJ | ME | Jamaica — signature watermark
# Owner: DJM (ONNYX) — Jamaica. If found elsewhere, contact ME.
# ONNYX · ONNX · DJM · DJ · ME · Jamaica
